auth:
  replicas: 1
  image:
    repository: ricoharsono/huatah-auth
    tag: latest
  dbHost: "mysql-igokochi-service.default.svc.cluster.local"
paynow:
  replicas: 1
  image:
    repository: ricoharsono/paynow
    tag: latest
  phone: "87956046"
backend:
  replicas: 2
  image:
    repository: ricoharsono/igokochi-backend
    tag: d1293c02
  authBaseUrl: "http://igokochi-auth-service:8081"
  dbHost: "mysql-igokochi-service"
  dbPort: "3306"
frontend:
  replicas: 2
  image:
    repository: ricoharsono/igokochi-frontend
    tag: "d1293c02"
  apiBaseUrl: "https://igokochihouse.com/api"
mysql:
  image:
    tag: "8.0"
  storage: 10Gi
  nodePort: 30306
