apiVersion: apps/v1
kind: Deployment
metadata:
  name: huatah-deployment
  labels:
    app: huatah
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: huatah
  template:
    metadata:
      name: huatah-pod
      labels:
        app: huatah
    spec:
      containers:
        - name: huatah
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: huatah-service-np
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: huatah
