apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-huatah
  labels:
    app: mysql-huatah
spec:
  serviceName: mysql-huatah
  replicas: 1
  selector:
    matchLabels:
      app: mysql-huatah
  template:
    metadata:
      labels:
        app: mysql-huatah
    spec:
      containers:
        - name: mysql
          image: mysql:{{ .Values.mysql.image.tag }}
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: huatah-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: huatah-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: huatah-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: huatah-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-huatah-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-huatah-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-huatah
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      nodePort: {{ .Values.mysql.nodePort }}
  selector:
    app: mysql-huatah
