apiVersion: batch/v1
kind: CronJob
metadata:
  name: huatah-nba-cronjob
spec:
  schedule: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: huatah-nba
              image: {{ .Values.scrapers.image.repository }}:{{ .Values.scrapers.image.tag }}
              imagePullPolicy: Always
              env:
                - name: RUN_MODE
                  value: "once"
                - name: LEAGUE_NAMES
                  value: {{ .Values.scrapers.nba.leagueNames | quote }}
                - name: MY_URL
                  value: {{ .Values.scrapers.myUrl | quote }}
                - name: LEAGUE_CODE
                  value: {{ .Values.scrapers.nba.leagueCode | quote }}
                - name: TYPE
                  value: {{ .Values.scrapers.nba.type | quote }}
                - name: REDIS_HOST
                  value: "redis"
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: huatah-secret
                      key: REDIS_PASSWORD
                - name: REDIS_KEY
                  value: "scraper:nba"
                - name: REDIS_TTL
                  value: "900"