{{- if .Values.scrapers.nfl }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: huatah-nfl-cronjob
spec:
  schedule: "3,8,13,18,23,28,33,38,43,48,53,58 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: huatah-nfl
              image: {{ .Values.scrapers.image.repository }}:{{ .Values.scrapers.image.tag }}
              imagePullPolicy: Always
              env:
                - name: RUN_MODE
                  value: "once"
                - name: LEAGUE_NAMES
                  value: {{ .Values.scrapers.nfl.leagueNames | quote }}
                - name: MY_URL
                  value: {{ .Values.scrapers.myUrl | quote }}
                - name: LEAGUE_CODE
                  value: {{ .Values.scrapers.nfl.leagueCode | quote }}
                - name: TYPE
                  value: {{ .Values.scrapers.nfl.type | quote }}
                - name: REDIS_HOST
                  value: "redis"
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: huatah-secret
                      key: REDIS_PASSWORD
                - name: REDIS_KEY
                  value: "scraper:nfl"
                - name: REDIS_TTL
                  value: "900"
{{- end }}
